sql = [("Cash and cash equivalents ", "SELECT cash_and_equiv FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Short-term investments ", "SELECT short_term_invest FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Accounts receivable - net ", "SELECT net_account_receiv FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Inventory ", "SELECT inventory FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Supplies ", "SELECT supplies FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total current assets ", "SELECT total_current_assets FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Investments ", "SELECT investments FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Land ", "SELECT land FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Land improvements ", "SELECT land_improvements FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Buildings ", "SELECT buildings FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Equipment ", "SELECT equipment FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Less: accumulated depreciation ", "SELECT accumulated_depreciation FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Property, plant & equip. - net ", "SELECT net_property FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Goodwill ", "SELECT goodwill FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Other intangible assets ", "SELECT other_intangible_assets FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total intangible assets ", "SELECT total_intangible_assets FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Other assets ", "SELECT other_assets FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total assets ", "SELECT total_assets FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Short-term loans payable ", "SELECT short_term_loans_payable FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Current portion of long-term debt ", "SELECT current_long_term_debt FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Accounts payable ", "SELECT accounts_payable FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Accrued compensation and benefits ", "SELECT accrued_comp_benefits FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Income taxes payable ", "SELECT income_taxes_payable FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Other accrued liabilities ", "SELECT other_liabilities FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Deferred revenues ", "SELECT deferred_revenues FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total current liabilities ", "SELECT total_current_liabilities FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Notes payable ", "SELECT notes_payable FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Bonds payable ", "SELECT bonds_payable FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Deferred income taxes ", "SELECT deferred_income_taxes FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total long-term liabilities ", "SELECT total_longterm_liabilities FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total liabilities ", "SELECT total_liabilities FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Common stock ", "SELECT common_stock FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Retained earnings ", "SELECT retained_earnings FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Accum other comprehensive income ", "SELECT other_comp_income FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Less: Treasury stock ", "SELECT treasury_stock FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total stockholders' equity ", "SELECT total_stockholders_equity FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
("Total liabilities & stockholders' equity ", "SELECT total_liabilities_stockholders_equity FROM internal_db WHERE company_name = 'Example Corporation' AND financial_quarter = 'fourth_quarter'"),
]

def getsql():
    return sql